lessons
ausblick
	^Lesson title: 'Ausblick' 
	lesson: 
'"
Wo erfahre ich mehr?
* http://de.wikipedia.org/wiki/Smalltalk_(Programmiersprache) - Deutscher Wikipedia-Artikel (das engl. Pendant http://en.wikipedia.org/wiki/Smalltalk gefällt mir aber besser)
* http://www.smalltalk.org - Old fashioned aber aktuelle Website der Community
* https://github.com/ofi/smalltalk-stuff - Ressourcen zu diesem Vortrag und Linksammlung
* Bei einem Bier mit mir. ;-)

Danke für Euer Interesse!
"
	ProfStef first.'