lessons
ausblick
	^Lesson title: 'Ausblick' 
	lesson: 
'"
Wer benutzt Smalltalk heute?
- Softwaretechnische Forschungseinrichtungen, z. B. inria.fr.
- Organisationen, in denen die Zeit von der Anforderung bis zur Realisierung Geld wert ist, z. B. Börsen und Banken.
- Menschen, die lieber für eine Lösung als für einen Compiler arbeiten, z. B. ich. ;-)

Wo erfahre ich mehr?
* http://de.wikipedia.org/wiki/Smalltalk_(Programmiersprache) - Deutscher Wikipedia-Artikel (das engl. Pendant http://en.wikipedia.org/wiki/Smalltalk gefällt mir aber besser)
* http://www.smalltalk.org - Old fashioned aber aktuelle Website der Community
* https://github.com/ofi/smalltalk-stuff - Ressourcen zu diesem Vortrag und Linksammlung
* Bei einem Bier mit mir. ;-)

Danke für Euer Interesse!
"
	ProfStef next.'