lessons
entwicklung
	^Lesson title: 'Nicht nur die Batterien sind enthalten' 
	lesson: 
'"
Zur Umgebung gehört eine Fülle von Werkzeugen...
...für das Programmieren im Kleinen:

	Browser und Inspektoren für Klassen, Objekte, Prozesse, Fenster, Einstellungen, Zustände, Profiling...

...und im Großen:

	Monticello zur Paketverwaltung,
	Metacello für Konfigurationsverwaltung und Dependency Management,
	Test Runner für SUnit und andere Tests,
	''ZeroConf''-Skripte zur Automatisierung
	
Massen von externen (meistens freien) Paketen und Frameworks für Codemetriken, Visualierung, DSLs, Application Server, etc.
"
	ProfStef next.'