lessons
geschichte
	^Lesson title: 'Informatik vs. BWL - 1 : 2' 
	lesson: 
'"
Notizen zur Geschichte:

Wer hat''s erfunden? - Alan Kay, Adele Goldberg et al. (Xerox Parc in Palo Alto, 1972-1980).

Wer stand Pate? - OO-Konzepte aus Simula (Norsk Regnesentral in Oslo, 1967) und die Garbage Collection aus Lisp (MIT, 1958 spezifiziert).

Was kam dabei noch heraus? - Grafische Fensteroberflächen, Unit-Tests, Design Pattern...

Welche Sprachen beeinflusste Smalltalk? - Objective-C, Java, Ruby, Self, PHP 5, Dart, AppleScript, Python, Groovy, Scala, Perl 6, Common Lisp Object System, ...

Wieso blieb der kommerzielle Erfolg aus?
- Bis Anfang der 90er stellte Smalltalk hohe Hardwareanforderungen. Deshalb dominierten C und später C++ aus Kostengründen.
- Smalltalk war teuer bis 1996 (freies Release von Squeak), und unterschiedliche Hersteller hatten inkompatible Klassenbibliotheken (oft lizenzrechtlich bedingt).
- Java ist kostenlos, monarchistisch genormt und bot Allianzen gegen die Windows-Dominanz, nicht zuletzt wegen ''billigerer'' Programmierer mit C-Migrationshintergrund.

Wer benutzt Smalltalk heute?
- Softwaretechnische Forschungseinrichtungen, z. B. inria.fr.
- Organisationen, in denen die Zeit von der Anforderung bis zur Realisierung Geld wert ist, z. B. Börsen und Banken.
- Menschen, die lieber für eine Lösung als für einen Compiler arbeiten, z. B. ich. ;-)
"
	ProfStef next.'