lessons
geschichte
	^Lesson title: 'Informatik vs. BWL - 1 : 2' 
	lesson: 
'"
Notizen zur Geschichte:

Wer hat''s erfunden? - Alan Kay, Adele Goldberg et al. (Xerox Parc in Palo Alto, 1972-1980).

Wer stand Pate? - OO-Konzepte aus Simula (Norsk Regnesentral in Oslo, 1967) und die Garbage Collection aus Lisp (MIT, 1958 spezifiziert).

Was kam dabei noch heraus? - Grafische Fensteroberflächen, Unit-Tests, Design Pattern...

Welche Sprachen beeinflusste Smalltalk? - Objective-C, Java, Ruby, Self, PHP 5, Dart, AppleScript, Python, Groovy, Scala, Perl 6, Common Lisp Object System, ...

Wieso blieb der kommerzielle Erfolg aus?
- Bis Anfang der 90er stellte Smalltalk hohe Hardwareanforderungen. Deshalb dominierten C und später C++ aus Kostengründen.
- Smalltalk war teuer bis 1996 (freies Release von Squeak), und unterschiedliche Hersteller hatten inkompatible Klassenbibliotheken (oft lizenzrechtlich bedingt).
- Java ist kostenlos, monarchistisch genormt und bot Allianzen gegen die Windows-Dominanz, nicht zuletzt wegen ''billigerer'' Programmierer mit C-Migrationshintergrund.

Welche technischen Gründe sprechen heute gegen einen Smalltalk-Einsatz?
- Smalltalk kennt keine ""Code Security"", d. h. jeder mit Zugriff auf das System (Image) kann durch fehlerhafte oder absichtliche Änderung einer Top-Level-Klasse die Anwendung sabotieren.
- Das Fehlen von Namensräumen, weshalb Kollisionen von Klassenbezeichnern nur durch Konvention verhindert werden können. VisualWorks hat deshalb seit Jahren die Syntax um Namensräume erweitert.
"
	ProfStef next.'