lessons
geschichte
	^Lesson title: 'Über 40 Jahre Smalltalk' 
	lesson: 
'"
Notizen zur Geschichte:

Wer hat''s erfunden? - Alan Kay, Adele Goldberg et al. (Xerox Parc in Palo Alto, 1972-1980).

Wer stand Pate? - OO-Konzepte aus Simula (Norsk Regnesentral in Oslo, 1967) und die Garbage Collection aus Lisp (MIT, 1958 spezifiziert).

Was kam dabei noch heraus? - Grafische Fensteroberflächen, Unit-Tests, Design Pattern...

Welche Sprachen beeinflusste Smalltalk? - Objective-C, Java, Ruby, Self, PHP 5, Dart, AppleScript, Python, Groovy, Scala, Perl 6, Common Lisp Object System, ...

"
	ProfStef next.'