lessons
heute
	^Lesson title: 'Smalltalk in der Gegenwart' 
	lesson: 
'"
Wer benutzt Smalltalk heute?
- Softwaretechnische Forschungseinrichtungen, z. B. inria.fr.
- Organisationen, in denen die Zeit von der Anforderung bis zur Realisierung Geld wert ist, z. B. Börsen und Banken.
- Menschen, die lieber für eine Lösung als für einen Compiler arbeiten, z. B. ich. ;-)

Praktische Beispiele:
* Demo ''CalendaryWeek'' und ''CalWeekWebApp '' JETZT.
"
	ProfStef next.'