lessons
objektRegel4a
	^Lesson title: 'Regel 4: Ausnahmen' 
	lesson: 
'"
Nicht alles lässt sich durch Versenden von Nachrichten erreichen. Manchmal muss einfach direkt etwas getan werden, und deshalb sind folgende Fälle keine Nachrichtensendungen:

- Variablendeklarationen allokieren nur Platz unter einem Namen und werden nicht einmal ausgeführt.

- Zuweisungen an eine Variable führt zu deren neuer Bindung innerhalb ihres Definitionsraums (scope).

- Rückgaben lösen nur den Transport eines Ergebnisses zurück an einen Sender aus.

- Primitive Methoden sind innerhalb der virtuellen Maschine implementiert. Ihr Aufruf erfolgt durch ein ''Pragma'', z. B. <primitive: ''primDigitDivNegative'' module:''LargeIntegers''>
"

	ProfStef next.'